package pthtml;
#!/usr/bin/perl
#html module
use strict;
use Win32::Console::ANSI;
use Term::ANSIColor;
#use warnings;

#General Block
my @ccdata;

	sub LOAD_ARR 
	{
		@ccdata = @_;
	}
	
	sub CLEAN_ARR 
	{
		@ccdata = undef;
	}

	sub PRINT_ARR 
	{
		for (0..$#ccdata) 
		{
			print $ccdata[$_]."\n";
		}
	}
	
#END General Block

#Common Cause Maintenance HTML
	sub CCM_HTML_BODY 
	{
		my ($count,$rows,%perltap) = @_;
		$perltap{ccfrep} = $perltap{ccfrep}."\t<tr class=\"leader\" title=\"Leader Ticket\">" if $perltap{cid} =~ /$perltap{leader}/;
		$perltap{ccfrep} .= "\t<tr class=\"odd\">" if $rows == 1 and $perltap{cid} !~ /$perltap{leader}/;
		$perltap{ccfrep} .= "\t<tr class=\"even\">" if $rows == 2 and $perltap{cid} !~ /$perltap{leader}/;
		$perltap{ccfrep} .= "\n\t\t<td>".$count."</td>\n\t\t<td>".$perltap{phone}."</td>\n\t\t<td><a href=\"http://wolfgang.czncorp.com/sh/servlet/RequestHandler?callId=".$perltap{cid}."&amp;actionNum=".$perltap{tcount}."&amp;task=BnEngViewCallsTexts&amp;listPclTarget=&amp;boardPclTarget=&amp;action=runQuery&amp;source=pgEngCallSearchRes&amp;textFT=72227448\" target=\"_blank\">".$perltap{cid}."</a></td>\n\t\t<td>".$perltap{report_code}."</td>\n\t\t<td>".$perltap{status}."</td>\n\t\t<td>".$perltap{address}."</td>\n\t\t<td>".$perltap{report_date}."</td>\n\t\t<td>".$perltap{commit_date}."</td>\n\t\t<td>".$perltap{cbr}."</td>\n\t\t<td>".$perltap{cust_name}."</td>\n\t</tr>\n" if $perltap{cid} =~ /$perltap{leader}/;
		$perltap{ccfrep} .= "\n\t\t<td>".$count."</td>\n\t\t<td>".$perltap{phone}."</td>\n\t\t<td><a href=\"http://wolfgang.czncorp.com/sh/servlet/RequestHandler?callId=".$perltap{cid}."&amp;actionNum=".$perltap{tcount}."&amp;task=BnEngViewCallsTexts&amp;listPclTarget=&amp;boardPclTarget=&amp;action=runQuery&amp;source=pgEngCallSearchRes&amp;textFT=72227448\" target=\"_blank\">".$perltap{cid}."</a></td>\n\t\t<td>".$perltap{report_code}."</td>\n\t\t<td>COMMON CAUSE</td>\n\t\t<td>".$perltap{address}."</td>\n\t\t<td>".$perltap{report_date}."</td>\n\t\t<td>".$perltap{commit_date}."</td>\n\t\t<td>".$perltap{cbr}."</td>\n\t\t<td>".$perltap{cust_name}."</td>\n\t</tr>\n" if $perltap{cid} !~ /$perltap{leader}/;
		
		if ($rows == 1) 
		{
			$rows = 2;
		} 
		elsif ($rows == 2) 
		{
			$rows = 1;
		}
		
		$count ++;
		return($count,$rows,%perltap);
	}
		
	sub CCM_HTML_CLOSE 
	{
		my ($count,%perltap) = @_;
		$perltap{ccfrep} .= "</table>\n<p>There are ".($count - 1)." tickets in this Common Cause.</p>\n";
		$perltap{ccfrep} .= "<p><b>Clipboard data for Common Cause Log:</b><br>\n<form name=\"CCLOG\">\n<textarea " .
			"id=\"LOG\" rows=\"4\" readonly style=\"width:60%;\">".
			$perltap{datestamp}."\t".$perltap{leader}."\t".$perltap{comcause}."\t".$perltap{env}."\t".($count - 1)."\tN/A\t".
			$perltap{con_status}."\t".$perltap{LAM}."\t".$perltap{rep_center}."\t".$perltap{town}."</textarea>\n</form>\n</p>\n";
		$perltap{ccfrep} .= "<p><b>Clipboard data for Excel:</b><br>\n<form name=\"CCCLIP\">\n<textarea id=\"CLIP\" rows=\"10\" readonly style=\"width:60%;\">\n".$perltap{newclip}."</textarea>\n</form>\n</p>\n";
		$perltap{ccfrep} .= "\n</body>\n</html>";
		return(%perltap);
	}
#END Common Cause Maintenance HTML
		
#Common Cause Finder HTML
	sub CCF_HTML_HEAD 
	{
		my ($title,%perltap) = @_;
		#---------------------------------------------------------
		$perltap{ccfrep} = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"
			   \"http://www.w3.org/TR/html4/loose.dtd\">
		<html>
		<head>
			<title>".$title."</title>
		</head>
		<body>
		<style type=\"text/css\">
			table {border:1px solid black;border-collapse:collapse;color:black;font-size:100%;table-layout:fixed;}
			th {
				font-weight:bold;border:1px solid gray;border-collapse:collapse;font-size:100%;background-color:#FFC000;padding-left:10px;padding-right:10px;padding-bottom:2px;padding-top:2px;text-align:left;white-space:nowrap;
				}
			td {
				border:1px solid gray;border-collapse:collapse;padding-left:10px;padding-right:10px;padding-bottom:2px;padding-top:2px;font-size:100%;color:black;white-space:nowrap;
				}
			.even {background-color:#EEEEEE;}
			.odd {background-color:#82CBDA;}
			.leader {background-color:pink;}
			.even:hover {background-color:orange;}
			.odd:hover {background-color:orange;}
			.leader:hover {background-color:red;}
			a:visited {color:gray;text-decoration:none;}
			a:hover {background-color:black;color:white;}
			#EInfo {border: 1px solid #ccc;
					display: none;
					font-size: 14px;
					margin-top: -2px;
					padding: 1px;
					background: white;
					text-align: left;
					position: absolute;
					margin-bottom: 0px;
					margin-left: 13px;
					text-transform: uppercase;}
			.even:hover #EInfo {display: inline;}
			.odd:hover #EInfo {display: inline;}
		</style>
		<p>Generated by PerlTap on ".$perltap{datestamp}." @ ".$perltap{timestamp}."<br>\n";
		#---------------------------------------------------------
		$perltap{ccfrep} .= "Report Code\(s\): ".$perltap{ccfilter}."<br>
		Status Type\(s\): ".$perltap{stfilter}."</p>
		<table>
			<tr>
				<th>#</th>
				<th>TN#</th>
				<th>Call ID</th>
				<th>RptCode</th>
				<th>Status</th>
				<th>Office</th>
				<th>Report Date</th>
				<th>Commit Date</th>
				<th>CBR</th>
				<th>Customer</th>
			</tr>" if $title eq "PerlTap CCFinder Report";
		#---------------------------------------------------------
		$perltap{ccfrep} .= "<p>
		<table>
			<tr><td style=\"text-align:right;font-weight:bold;\">Common Cause: </td><td><b><a href=\"http://wolfgang.czncorp.com/sh/RTS_HTML_Pages/Customized_Pages/UtilityJSPs/CommonCause/CommonCauseMaintenance.jsp?getResults=yes&commonCauseId=".$perltap{comcause}."\">".$perltap{comcause}."</a></b></td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">Leader CID: </td><td>".$perltap{leader}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">LAM: </td><td>".$perltap{LAM}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">VN Exchange: </td><td>".$perltap{vn_exchange}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">Exchange: </td><td>".$perltap{exchange}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">Rep Center: </td><td>".$perltap{rep_center}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">Town: </td><td>".$perltap{town}."</td></tr>
			<tr><td style=\"text-align:right;font-weight:bold;\">Office: </td><td>".$perltap{office}."</td></tr>
		</table>
		</p>
		<table>
			<tr>
				<th>#</th>
				<th>TN#</th>
				<th>Call ID</th>
				<th>RptCode</th>
				<th>Status</th>
				<th>Address</th>
				<th>Rpt Date</th>
				<th>Com Date</th>
				<th>CBR</th>
				<th>Customer</th>
			</tr>" if $title =~ /PerlTap Common Cause - /;
		#---------------------------------------------------------
		$perltap{ccfrep} .= "</p>
		<table>
			<tr>
				<th>#</th>
				<th>TN#</th>
				<th>Call ID</th>
				<th>Report</th>
				<th>Status</th>
				<th>LAM</th>
				<th>Rep Center</th>
				<th>Exchange</th>
				<th>Report Date</th>
				<th>Commit Date</th>
				<th>Customer</th>
			</tr>" if $title =~ /PerlTap Testboard Results/;
		#---------------------------------------------------------
		return (%perltap);
	}
		
	sub CCF_HTML_BODY 
	{
		my ($count,$rows,%perltap) = @_;
		#print $rows." ".$count." ".$perltap{report_code}."_".$perltap{status}."_\n" if $perltap{debug} eq "ON";
		$perltap{ccfrep} .= "\t<tr class=\"odd\">" if $rows == 1;
		$perltap{ccfrep} .= "\t<tr class=\"even\">" if $rows == 2;
		$perltap{ccfrep} .= "\n\t\t<td>".$count."</td>\n\t\t<td>".$perltap{phone}."</td>
		\n\t\t<td><a href=\"http://wolfgang.czncorp.com/sh/servlet/RequestHandler?callId=".$perltap{cid}."&amp;actionNum=".$perltap{tcount}."&amp;task=BnEngViewCallsTexts&amp;listPclTarget=&amp;boardPclTarget=&amp;action=runQuery&amp;source=pgEngCallSearchRes&amp;textFT=72227448\" target=\"_blank\">".$perltap{cid}."</a><span id=\"EInfo\"><b>".$perltap{report_code}."</b> | ".$perltap{status}." | ".$perltap{LAM}." | ".$perltap{office}." | ".$perltap{rep_center}." | ".$perltap{vn_exchange}."</span></td>\n\t\t<td>".$perltap{report_code}."</td>\n\t\t<td>".$perltap{status}."</td>\n\t\t<td>".$perltap{office}."</td>\n\t\t<td>".$perltap{report_date}."</td>\n\t\t<td>".$perltap{commit_date}."</td>\n\t\t<td>".$perltap{cbr}."</td>\n\t\t<td>".$perltap{cust_name}."</td>\n\t</tr>\n";
		$perltap{dsltnlist} = $perltap{dsltnlist}.$perltap{phone}."\n" if $perltap{report_code} =~ /DSL/;
		$perltap{othtnlist} = $perltap{othtnlist}.$perltap{phone}."\n" if $perltap{report_code} !~ /DSL/;
		#<span id=\"EInfo\"><b>".$perltap{report_code}."</b> | ".$perltap{status}." | ".$perltap{office}." | ".$perltap{rep_center}." | ".$perltap{vn_exchange}."</span>
		
		if ($rows == 1) 
		{
			$rows = 2;
		} 
		elsif ($rows == 2) 
		{
			$rows = 1;
		}
		
		$count ++;
		return($count,$rows,%perltap);
	}

	sub CCF_HTML_CLOSE
	{
		my ($count,%perltap) = @_;
		$perltap{ccfrep} .= "</table>\n<p>There were ".($count - 1)." matches out of ".$perltap{cctotal}." tickets.</p>\n";
		$perltap{ccfrep} .= "<p><b>DSL TN's for Bulk Test:</b><br>\n<form name=\"DSLTN\">\n<textarea id=\"DSL\" rows=\"10\" readonly>\n".$perltap{dsltnlist}."</textarea>\n</form>\n</p>\n" if $perltap{ccfilter} =~ /DSL|ALL/;
		$perltap{ccfrep} .= "<p><b>Other copied TN's:</b><br>\n<form name=\"OTHTN\">\n<textarea id=\"OTH\" rows=\"10\" readonly>\n".$perltap{othtnlist}."</textarea>\n</form>\n</p>\n" if $perltap{ccfilter} =~ /DSL|ALL/ and $perltap{othtnlist} =~ /\S+/;
		$perltap{ccfrep} .= "\n</body>\n</html>";
		return(%perltap);
	}
# END Common Cause Finder

#LoopCare HTML
	sub LC_DSLDIG 
	{
		my (%perltap) = @_;
		my ($vara,$varb,$varc) = $ccdata[$_] =~ /(.*):\s+(\S+)\s+(\S+)/;
		print colored['black on_white'], $vara.":".$varb.":".$varc.":" if $perltap{debug} eq "ON";
		print color("White"), " \n" if $perltap{debug} eq "ON";
		$perltap{resultsclip} .= "<tr><td>".$vara."</td><td>".$varb."</td><td>".$varc."</td></tr>" if $ccdata[$_] =~ /\S+/ and $ccdata[$_] !~ /SERVICE TYPE:|SERVICE MODE:|xTU|STATUS|LINE CODING:|LINE TYPE:|CPE|MINIMUM NOISE MARGIN|MAXIMUM NOISE MARGIN|TARGET NOISE MARGIN|RATE ADAPT MODE/i and $vara;
		return(%perltap);
	}
		
	sub LC_LOOPX 
	{
		my (%perltap) = @_;
		
		if ($perltap{count}{crafta} > 0 and $perltap{count}{craftb} > 0) 
		{
			$perltap{resultsclip} = "<tr><td><b>CRAFT: DC SIGNATURE (KOHMS) </b></td><td><b>VOLTS</b></td><td><b>PAIR</b></td></tr>";
			
			for ($perltap{count}{crafta}..$perltap{count}{craftb}) 
			{
				my ($a,$b,$c) = $ccdata[$_] =~ /(\S+) (.*) (\w\-\w)/;
				$perltap{resultsclip} .= "<tr><td>".$a."</td><td>".$b."</td><td>".$c."</td></tr>" if $c;
				$perltap{resultsclip} .= "<tr><td>--</td><td>--</td><td>--</td></tr>" if !$c;
			}
		}
		
		if ($perltap{count}{dcsiga} > 0 and $perltap{count}{dcsigb} > 0) 
		{	
			$perltap{resultsclip} .= "<tr><td><b>DC SIGNATURE (KOHMS) </b></td><td><b>VOLTS</b></td><td><b>PAIR</b></td></tr>";
			
			for ($perltap{count}{dcsiga}..$perltap{count}{dcsigb}) 
			{
				my ($a,$b,$c) = $ccdata[$_] =~ /(\S+) (.*) (\w\-\w)/ if $ccdata[$_] =~ /(\S+) (.*) (\w\-\w)/;
				$perltap{resultsclip} .= "<tr><td>".$a."</td><td>".$b."</td><td>".$c."</td></tr>" if $c;
				$perltap{resultsclip} .= "<tr><td>--</td><td>--</td><td>--</td></tr>" if !$c;
			}
		}
		
		if ($perltap{count}{acsiga} > 0 and $perltap{count}{acsigb} > 0) 
		{	
			$perltap{resultsclip} .= "<tr><td><b>AC SIGNATURE (KOHMS) </b></td><td><b>UFARAD</b></td><td><b>PAIR</b></td></tr>";
			
			for ($perltap{count}{acsiga}..$perltap{count}{acsigb}) 
			{
				my ($a,$b,$c) = $ccdata[$_] =~ /(\d+) (\S+) .*?(\w\-\w)/ if $ccdata[$_] =~ /(\d+) (\S+) .*?(\w\-\w)/;
				$perltap{resultsclip} .= "<tr><td>".$a."</td><td>".$b."</td><td>".$c."</td></tr>" if $c;
				$perltap{resultsclip} .= "<tr><td>--</td><td>--</td><td>--</td></tr>" if !$c;
			}
		}
		
		if ($perltap{count}{centra} > 0 and $perltap{count}{centrb} > 0) 
		{	
			$perltap{resultsclip} .= "<tr><td><b>CENTRAL OFFICE</b></td><td colspan=2>";
			
			for ($perltap{count}{centra}..$perltap{count}{centrb}) 
			{
				my $a = $ccdata[$_];
				chomp $a;
				$perltap{resultsclip} .= $a."<br>" if $a;
			}
			
			$perltap{resultsclip} .= "</td></tr>";
		}
		
		$perltap{resultsclip} .= "<tr><td><b>LOOP LENGTH </b></td><td colspan=2>".$perltap{count}{length}." FT</td></tr>" if $perltap{count}{length} =~ /\S+/;
		$perltap{resultsclip} .= "<tr><td><b>BALANCE </b></td><td colspan=2>".$perltap{count}{balance}."%</td></tr>" if $perltap{count}{balance} =~ /\S+/;
		CLEAN_ARR();
		return(%perltap);
	}
		
	sub LC_COMPLETE 
	{
		my (%perltap) = @_;
		$perltap{summaryclip} =~ s/\n|\r//g;
		$perltap{resultsclip} =~ s/\n|\r//g;
		
		if ($perltap{lctype} eq "DSL") 
		{
			$perltap{resultsclip} = "<tr><td> </td><td><b>DOWNLOAD</b></td><td><b>UPLOAD</b></td></tr>".$perltap{resultsclip};
			$perltap{resultsclip} = "<tr><td>SERVICE TYPE</td><td colspan=\"2\">".$perltap{dsl_service}."</td></tr>" .
				#"<tr><td>LINE CODING</td><td colspan=\"2\">".$perltap{dsl_coding}."</td></tr>" .
				"<tr><td>LINE TYPE</td><td colspan=\"2\">".$perltap{dsl_type}."</td></tr>".$perltap{resultsclip};
			$perltap{resultsclip} .= "<tr><td><i>\(Last 24 hours\)</i></td><td><b>NEAR</b></td><td><b>FAR</b>" .
				"</td></tr>" if $perltap{sync_loss}{near} > 0 or $perltap{sync_loss}{far} > 0 or 
				$perltap{link_loss}{near} > 0 or $perltap{link_loss}{far} > 0 or 
				$perltap{errored_seconds}{near} > 0 or $perltap{errored_seconds}{far} > 0 or 
				$perltap{crc_anomaly}{near} > 0 or $perltap{crc_anomaly}{far} > 0 or 
				$perltap{fec_event}{near} > 0 or $perltap{fec_event}{far} > 0;
			$perltap{resultsclip} .= "<tr><td>ERRORED SECONDS</td><td>".$perltap{errored_seconds}{near}."</td><td>".
				$perltap{errored_seconds}{far}."</td></tr>" if $perltap{errored_seconds}{near} > 0 or $perltap{errored_seconds}{far} > 0;
			$perltap{resultsclip} .= "<tr><td>LOSS OF LINK</td><td>".$perltap{link_loss}{near}."</td><td>".$perltap{link_loss}{far}.
				"</td></tr>" if $perltap{link_loss}{near} > 0 or $perltap{link_loss}{far} > 0;
			$perltap{resultsclip} .= "<tr><td>LOSS OF SYNC</td><td>".$perltap{sync_loss}{near}."</td><td>".$perltap{sync_loss}{far}.
				"</td></tr>" if $perltap{sync_loss}{near} > 0 or $perltap{sync_loss}{far} > 0;
			$perltap{resultsclip} .= "<tr><td>CRC ANOMALIES</td><td>" . $perltap{crc_anomaly}{near} . "</td><td>" . $perltap{crc_anomaly}{far} . 
				"</td></tr>" if $perltap{crc_anomaly}{near} > 0 or $perltap{crc_anomaly}{far} > 0;
			$perltap{resultsclip} .= "<tr><td>FEC EVENTS</td><td>" . $perltap{fec_event}{near} . "</td><td>" . $perltap{fec_event}{far} . 
				"</td></tr>" if $perltap{fec_event}{near} > 0 or $perltap{fec_event}{far} > 0;
		}
		
		$perltap{resultsclip} = "<table border=\"1\" style=\"width:355px;font-size:90%;background-color:lightblue\"><tr><th><b>LoopCare Results:</b></th></tr><tr><td><b>Outcome: </b>".$perltap{vercode}."</td></tr><tr><td><b>Summary: </b><br>".$perltap{summaryclip}."</td></tr><tr><td><table border=\"1\" style=\"width:355px;font-size:95%;\">".$perltap{resultsclip}."</table></td></tr></table>\n";
		return(%perltap);
	}
#END LoopCare HTML

#TestBoard HTML
	sub TB_HTML_BODY 
	{
		my ($count,$rows,%perltap) = @_;
		#print $rows." ".$count." ".$perltap{report_code}."_".$perltap{status}."_\n" if $perltap{debug} eq "ON";
		$perltap{ccfrep} .= "\t<tr class=\"odd\">" if $rows == 1;
		$perltap{ccfrep} .= "\t<tr class=\"even\">" if $rows == 2;
		$perltap{ccfrep} .= "\n\t\t<td>".$count."</td>\n\t\t<td>".$perltap{phone}."</td>\n\t\t<td><a href=\"http://wolfgang.czncorp.com/sh/servlet/RequestHandler?callId=".$perltap{cid}."&amp;actionNum=".$perltap{tcount}."&amp;task=BnEngViewCallsTexts&amp;listPclTarget=&amp;boardPclTarget=&amp;action=runQuery&amp;source=pgEngCallSearchRes&amp;textFT=72227448\" target=\"_blank\">".$perltap{cid}."</a></td>\n\t\t<td>".$perltap{report_code}."</td>\n\t\t<td>TESTBOARD<span id=\"EInfo\"><b>".$perltap{LAM}."</b> | Office: ".$perltap{offnum}." | Cell: ".$perltap{cellnum}." | <a href=mailto:".$perltap{tech_sup}."\@ftr.com>Email TM</a></span></td>\n\t\t<td>".$perltap{LAM}."</td>\n\t\t<td>".$perltap{rep_center}."</td>\n\t\t<td>".$perltap{exchange}."</td>\n\t\t<td>".$perltap{report_date}."</td>\n\t\t<td>".$perltap{commit_date}."</td>\n\t\t<td>".$perltap{cust_name}."</td>\n\t\t</td>\n\t</tr>\n" if $perltap{tech_sup} ne "void";
		$perltap{ccfrep} .= "\n\t\t<td>".$count."</td>\n\t\t<td>".$perltap{phone}."</td>\n\t\t<td><a href=\"http://wolfgang.czncorp.com/sh/servlet/RequestHandler?callId=".$perltap{cid}."&amp;actionNum=".$perltap{tcount}."&amp;task=BnEngViewCallsTexts&amp;listPclTarget=&amp;boardPclTarget=&amp;action=runQuery&amp;source=pgEngCallSearchRes&amp;textFT=72227448\" target=\"_blank\">".$perltap{cid}."</a></td>\n\t\t<td>".$perltap{report_code}."</td>\n\t\t<td>TESTBOARD</td>\n\t\t<td>".$perltap{LAM}."</td>\n\t\t<td>".$perltap{rep_center}."</td>\n\t\t<td>".$perltap{exchange}."</td>\n\t\t<td>".$perltap{report_date}."</td>\n\t\t<td>".$perltap{commit_date}."</td>\n\t\t<td>".$perltap{cust_name}."</td>\n\t\t</td>\n\t</tr>\n" if $perltap{tech_sup} eq "void";
		
		if ($rows == 1) 
		{
			$rows = 2;
		} 
		elsif ($rows == 2) 
		{
			$rows = 1;
		}
		
		$count ++;
		return($count,$rows,%perltap);
	}
		
	sub TB_HTML_CLOSE 
	{
		my ($count,%perltap) = @_;
		$perltap{ccfrep} .= "</table>\n<p>There were ".($count - 1)." matches out of ".$perltap{ticket_total}." tickets.</p>\n";
		$perltap{ccfrep} .= "</table>\n<br><br><br>\n</body>\n</html>";
		return(%perltap);
	}
#END TestBoard HTML

#Test Code
	sub HTML_TAPSHEET 
	{
		my ($year,%perltap) = @_;
		my $html;
		print $perltap{newclip}."\n";
		my @data = split /\r/,$perltap{newclip};
		
		for(0..$#data) 
		{
			print $data[$_]."\n";
			$data[$_] =~ s/\t/<\/td><td>/g;
			print $data[$_]."\n";
			$html = $html."<tr><td>".$data[$_]."</td></tr>\n";
		}
		
		print ">>".$perltap{userprofile}."\\Desktop\\".$perltap{username}."\.html\n";
		print $html."\n";
		open FH, ">>".$perltap{userprofile}."\\Desktop\\".$perltap{username}."\.html";
		print FH $html;
		close(FH);
	}
#END Test Code

1;